[package]
name = "react-ds"
version = "0.1.0"
authors = ["Redrield <redrield@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-view = "0.5.2"
lazy_static = "1.4.0"
rust-embed = "5.1.0"
rocket = "0.4.2"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.41"
#ds = "0.3.2"
ds = { path = "../ds-rs" }
