[package]
name = "elm-ds"
version = "0.1.0"
authors = ["Redrield <redrield@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-view = "0.5.2"
lazy_static = "1.4.0"
rust-embed = "5.1.0"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.41"
ds = "1.0.0"
chrono = "0.4.9"
gilrs = "0.7.2"
spin = "0.5.2"
priomutex = "0.3.1"
actix-web = "1.0.8"
actix-rt = "0.2.5"
mime_guess = "2.0.1"
futures = "0.1.29"
env_logger = "0.7.1"
