name: Build Status
on: [push, pull_request]

env:
    CARGO_TERM_COLOR: always
    CI: false

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rust-toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: clippy
    - name: Install Dependencies
      run: |
        curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
        sudo apt-get install -y nodejs libudev-dev libx11-dev libxi-dev libpango1.0-dev libatk1.0-dev libsoup2.4-dev libgtk-3-dev libwebkit2gtk-4.0-dev
    - name: Install Cargo tools
      run: |
          cargo install cargo-deb && cargo install cargo-rpm
    - name: Build Frontend
      run: |
        make setup && make frontend
    - name: Build DEB
      run: |
          cargo deb
    - name: Build RPM
      run: |
          cargo rpm build
    - name: rust-clippy-check
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Ubuntu
    - name: Archive Raw Application
      uses: actions/upload-artifact@v2
      with:
        name: Conductor_ubuntu-latest
        path: target/release/conductor
    - name: Archive DEB
      uses: actions/upload-artifact@v2
      with:
          path: target/debian/*.deb
    - name: Archive RPM
      uses: actions/upload-artifact@v2
      with:
          path: target/release/RPMs/*.rpm
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: rust-toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: clippy
    - name: Build Application
      run: |
        make setup && make release
    - name: rust-clippy-check
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: macOS
    - name: Archive Application
      uses: actions/upload-artifact@v2
      with:
        name: macos-latest
        path: target/release/conductor
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt
      - name: Install Dependencies
        run: |
          curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
          sudo apt-get install -y nodejs libudev-dev libx11-dev libxi-dev libpango1.0-dev libatk1.0-dev libsoup2.4-dev libgtk-3-dev libwebkit2gtk-4.0-dev
      - name: Build frontend
        run: |
          make setup && make frontend
      - name: Formatter
        uses: mbrobbel/rustfmt-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
